apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - environment: dev
          - environment: staging
          - environment: production
  template:
    metadata:
      name: 'external-dns-{{.environment}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://kubernetes-sigs.github.io/external-dns/
          chart: external-dns
          targetRevision: 1.14.5
          helm:
            releaseName: external-dns
            values: |
              sources:
                - service
                - ingress
              policy: sync
              registry: txt
              txtOwnerId: external-dns-{{.environment}}
              domainFilters: []
              {{- if eq .environment "dev"}}
              logLevel: debug
              {{- end}}
        - repoURL: https://github.com/NicolasViaud/cluster-gitops.git
          targetRevision: main
          path: 'infrastructure/external-dns/overlays/{{.environment}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: external-dns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
