apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - environment: dev
          # - environment: staging
          # - environment: production
  template:
    metadata:
      name: 'grafana-{{.environment}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: grafana
          targetRevision: 8.7.1
          helm:
            releaseName: grafana
            valueFiles:
              - $values/infrastructure/grafana/values/common.yaml
              - $values/infrastructure/grafana/values/{{.environment}}.yaml
        - repoURL: https://github.com/NicolasViaud/cluster-gitops.git
          targetRevision: main
          ref: values
        - repoURL: https://github.com/NicolasViaud/cluster-gitops.git
          targetRevision: main
          path: 'infrastructure/grafana/overlays/{{.environment}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
